### ISSUE TITLE
Building the app fails with CLI v6.3.0

### ISSUE THREAD

**Issue by blefebvre** [blefebvre/aem-phonegap-kitchen-sink#67]
Steps to reproduce:

- download the app source from dev or stage, and build using the PhoneGap CLI v6.3.0

Result

- build fails with the following error:
```
com.telerik.plugins.nativepagetransitions/NativePageTransitions.m:10:17: error: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
  self = [super initWithWebView:theWebView]; 
```
